dependencies:
    - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
    evm_version: null
    solc:
        version: 0.6.12
        optimizer:
            enabled: true
            runs: 200

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
